#️⃣ Prefix Commands with a #
RedPRL/cooltt pull request #281
Opened 2021-08-31 23:29 UTC by TOTBWF

## Patch Description
This PR is a small tweak that prefixes "commands" like `print` and `normalize` with a `#` to avoid keyword creep, and make them visually distinct. This closes #277.

2021-08-31 23:43 UTC, jonsterling approved these changes
Looks good! thanks!

2021-09-01 01:31 UTC, favonia commented
My only objection is that I want to change `#t` and `#f` to something not starting with `#`.

2021-09-01 01:34 UTC, jonsterling commented
> My only objection is that I want to change `#t` and `#f` to something not starting with `#`. I hope something is a command **if and only if** it starts with `#`.

Oohhh, that's a good point. Yes, I guess they have to be renamed. Maybe `tt/ff`.

2021-09-01 18:36 UTC, favonia commented on src/core/Syntax.ml
> +        Uuseg_string.pp_utf_8 "⊤"
🔝

2021-09-01 19:01 UTC, jonsterling requested changes
I think I don't want to use \top,\bot for true/false because this promotes the identification of booleans with propositions... It could make the cofibration language a bit confusing.

Likewise it seems like the current parser would allow `tt` to be used for the true cofibration, but I find that confusing.

My preference would be for all those to be separate if that's ok with everyone.

2021-09-01 20:43 UTC, TOTBWF commented
Yeah, I can see how it would be somewhat misleading. I don't want to steal `top` and `bot` as keywords, as that could get kind of annoying, but I am struggling a bit to find names that are suggestive that dont:
- Steal common identifiers
- Don't suggest that propositions are booleans

2021-09-01 21:15 UTC, jonsterling commented
Thanks for the clarification @favonia @TOTBWF! My new proposal is:

1. We have cofibrations called `true` and `false`; these can optionally be written with the top/bottom unicode symbols. It is not unexpected for these to be keywords in a language.
2. We have booleans called `tt` and `ff`; once we add inductive types, these can be deleted.

2021-09-01 21:22 UTC, favonia commented
Revision: ✅ for true and ⛔ for false

2021-09-01 22:11 UTC, TOTBWF commented
In order to use `true` and `false`, you must include the following command:
```
#I-acknowledge-that-propositions-are-in-fact-not-booleans
```

Perhaps something could be added to the license as well.

2021-09-02 03:53 UTC, jonsterling approved these changes

2021-09-02 04:30 UTC, favonia commented
> In order to use `true` and `false`, you must include the following command:
> 
> ```
> #I-acknowledge-that-propositions-are-in-fact-not-booleans
> ```
> 
> Perhaps something could be added to the license as well.

Alternative proposal: the following binding will disable keywords `true` and `false`.
```
def _ = "use strict"
```

2021-09-02 04:33 UTC, favonia approved these changes
I thought I approved this PR? My memory is not working...

2021-09-02 16:57 UTC, merged