Implicit Total Space Conversion
RedPRL/cooltt pull request #322
Opened 2022-03-17 08:17 UTC by mmcqd

Hello! I'm a first time cooltt contributor :)

This PR makes implicit the conversion between a signature indexed type family and its total space (as implemented in #280).
Now instead of writing `fam # []`, one can write `fam` and instead of `fam # [ patches ]` one can write `fam as [ patches ]`. This takes cooltt one step closer to the original total space conversion proposal in #267. The definition of a category now looks like this:
```
def category : type :=
  sig (ob : type)
      (hom : sig (s : ob) (t : ob) → type)
      (idn : (x : ob) -> hom as [ s .= x | t .= x ])
      (seq : (f : hom) -> (g : hom as [ s .= f.t ]) -> hom as [ s .= f.s | t .= g.t ])
      (seqL : (f : hom) -> path {hom as [ s .= f.s | t .= f.t ]} {seq {idn {f.s}} f} f)
      (seqR : (f : hom) -> path {hom as [ s .= f.s | t .= f.t ]} {seq f {idn {f.t}}} f)
      (seqA : (f : hom) -> (g : hom as [ s .= f.t ]) -> (h : hom as [ s .= g.t ]) -> path {hom as [ s .= f.s | t .= h.t ]} {seq f {seq g h}} {seq {seq f g} h})
```
This PR also removes the `#` syntax for explicit total space conversion, and gives `as` the precedence that `#` used to have.

I may have violated some cooltt style guidelines or misunderstood some implementation details, and would be happy to refactor this as needed. I wasn't sure where to put the new tactic which handles this, so I put it in `Refiner.Structural`, but this may have been the wrong place.

If this goes well, I also have some ideas for making it more convenient to inhabit patched record types that I'd love to try!

2022-03-17 11:54 UTC, favonia commented
Thank you for your PR and we will take a careful look.

Quick response to this question:

> I may have violated some cooltt style

As long as you are (1) removing trailing whitespace, (2) using `ocp-indent` for OCaml indentation, and (3) being semi-consistent with the surrounding code (we do not have global naming convention etc.), then your coding style should be fine!

2022-03-17 17:39 UTC, mmcqd commented
> This looks really really cool. Btw what about writing `#` instead of `as`?

I agree that `#` would be nicer as the patch operator. Done.

2022-03-17 19:46 UTC, TOTBWF requested changes
Looks great, amazing first contribution :)

A couple of minor nits, mostly related to organization. With these changes, it seems to me that `Tactics.ml` would be a better home for these tactics, as it's more in line with `intro_implicit_connectives` et. al.

2022-03-17 23:03 UTC, mmcqd commented on src/core/Refiner.ml
> +  let intro_conversions (tac : T.Syn.tac) : T.Chk.tac =
I agree, I've moved it. Is `intro_conversions` a good name for this? Perhaps `intro_implicit_conversions` would be better? I made it plural with the expectation there might be more conversions of this style done in the future.

2022-03-17 23:05 UTC, mmcqd commented on src/core/Refiner.ml
> +  let total (vsign : (Ident.user * D.con) list) (vtm : D.con) : T.Chk.tac =
I agree it makes more sense there, but it depends on `quote_sign_codes`, which is also used by `patch_fields`. Should that be exposed by the refiner?

2022-03-18 15:48 UTC, favonia commented
> This looks really really cool. Btw what about writing `#` instead of `as`?

As a side issue that belongs to another PR, do we prefer to drop `#` completely? PS: it is widely accepted that either :genie: can do it or it is mathematically impossible.

2022-03-18 16:01 UTC, jonsterling commented
@favonia if we could drop it that would be awesome!

2022-03-18 16:38 UTC, TOTBWF commented on src/core/Refiner.ml
> +  let total (vsign : (Ident.user * D.con) list) (vtm : D.con) : T.Chk.tac =
Ah, good point. Perhaps the move is to expose `quantifiers` somewhere. Either way, this is a minor nit, and shouldn't hold up this PR. Great work!

2022-03-18 23:03 UTC, TOTBWF approved these changes
Looks great! Welcome to the 😎 zone

2022-03-18 23:22 UTC, mmcqd commented
> Looks great! Welcome to the 😎 zone

Cool! Looking forward to making some more contributions 👀. btw I can't merge the PR because I don't have write access, so one of you will have to do it

2022-03-19 02:00 UTC, merged